name: cli_pkg_test
version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  js: ^0.6.3
  grinder: ^0.9.0
  cli_pkg: {path: ..}
  test: ^1.16.7
dev_dependencies:
  node_interop: any
